### ISSUE TITLE
Unable to decrypt from Windows phone

### ISSUE THREAD

**Issue by adithyan** [dfirfpi/hotoloti#1]
I checked on my windows phone, I'm not able to find any .crypt files, only .db files exists (messages.db)
And it didn't work

**Comment by dfirfpi** [comment]
Hi @adithyan, your message is not clear but I guess you're talking about WhatsApp. The WhatsApp extractor does not work with winphone dbs... But you can "almost easily" use any sqlite browser to access the data if not encrypted.
